// <auto-generated />
namespace iClinic.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class annotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(annotation));
        
        string IMigrationMetadata.Id
        {
            get { return "201612161455525_annotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
